version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: piyush
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Piyush@03
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/piyush
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Piyush@03
      JWT_SECRET: TmV3U2VjcmV0S2V5Rm9yU3R1ZGVudEFwcEpXVFNlY3VyaXR5MTIz
    depends_on:
      - postgres

volumes:
  postgres_data: