spring.application.name=student-app

# Environment variables use karo
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/piyush}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Piyush@03}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
jwt.secret=${JWT_SECRET:TmV3U2VjcmV0S2V5Rm9yU3R1ZGVudEFwcEpXVFNlY3VyaXR5MTIz}